name: Playwright + Cucumber Tests

on:
  push:
    branches: [ main, rest ]
  pull_request:
    branches: [ main, rest ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm install

      - name: Verificar vulnerabilidades nas dependências
        run: npm audit

      - name: Instalar navegadores do Playwright
        run: npx playwright install --with-deps

      - name: Criar diretório para relatórios
        run: mkdir -p test-results

      - name: Executar testes Cucumber com Playwright
        run: npm testCI

      - name: Instalar k6
        run: |
          curl -L https://github.com/grafana/k6/releases/download/v0.51.0/k6-v0.51.0-linux-amd64.tar.gz -o k6.tar.gz
          tar -xzf k6.tar.gz
          sudo mv k6-v0.51.0-linux-amd64/k6 /usr/local/bin/
          rm -rf k6.tar.gz k6-v0.51.0-linux-amd64
      - name: Executar testes de performance com k6
        run: npm run performance

      - name: Fazer upload dos relatórios de teste como artefato
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            test-results/
            playwright-report/
            k6-report.json
