name: Playwright + Cucumber Tests

on:
  push:
    branches: [ main, rest ]
  pull_request:
    branches: [ main, rest ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm install

      - name: Instalar navegadores do Playwright
        run: npx playwright install --with-deps

      - name: Executar testes Cucumber com Playwright
        run: npm run test

      - name: Analisar com LLM (pular se SKIP_LLM=true)
        if: env.SKIP_LLM != 'true'
        run: npm run analyze
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SKIP_LLM: ${{ env.SKIP_LLM }}

      - name: Instalar k6
        run: |
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D83AC848
          sudo apt-get update
          sudo apt-get install k6

      - name: Executar testes de performance com k6
        run: k6 run marsair_test.js --out json=k6-report.json

      - name: Relatórios de Teste
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            test-results/
            playwright-report/
            k6-report.json